version: '3.0'

services:
  front:
    container_name: front
    build:
      context: ./project/interview-fe
    env_file:
      - ./project/.env.local
    volumes:
      - ./project/interview-fe:/app
    ports:
      - 5173:5173
    depends_on:
      - nginx
      - backend
    restart: always

  backend:
    container_name: backend
    build:
      context: ./project/interview-be
    env_file:
      - ./project/interview-be/.development.env
    volumes:
      - ./project/interview-be:/app
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:1.27.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./project/nginx:/etc/nginx/conf.d
      - ./project/certs:/etc/ssl/certs:ro

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./project/interview-be/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: